kind: Secret
apiVersion: v1
metadata:
  name: cloud-credentials
  namespace: openshift-adp
  uid: 0f13da64-0f09-4659-a621-b1e281757582
  resourceVersion: '138715'
  creationTimestamp: '2026-07-23T19:34:39Z'
  labels:
    dataprotectionapplication.name: velero
    openshift.io/oadp: 'True'
  managedFields:
    - manager: kubectl-create
      operation: Update
      apiVersion: v1
      time: '2026-07-23T19:34:39Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:data':
          .: {}
          'f:cloud': {}
        'f:type': {}
    - manager: manager
      operation: Update
      apiVersion: v1
      time: '2026-07-23T19:35:43Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:labels':
            .: {}
            'f:dataprotectionapplication.name': {}
            'f:openshift.io/oadp': {}
data:
  cloud: W2RlZmF1bHRdCmF3c19hY2Nlc3Nfa2V5X2lkPUFLSUFYTVFXRVlaTEdWWE1BUTYzCmF3c19zZWNyZXRfYWNjZXNzX2tleT1CcVh5enc2TmxML0Juem84cE9qZnZ6c3hUNGFGUDJ2ekNkNEdPN1pXCg==
type: Opaque
