apiVersion: velero.io/v1
kind: Restore
metadata:
  name: petclinic-app-restore-diff-ns
  namespace: openshift-adp
spec:
  backupName: petclinic-app-backup
  includedNamespaces:
    - petclinic-demo
  namespaceMapping:
    petclinic-demo: petclinic-restored-prod # CRITICAL: Maps old namespace -> new different namespace
  restorePVs: true                         # Streams data blocks straight into your ODF Ceph storage
  preserveNodePorts: true
  excludedResources:
    - nodes
    - events
    - events.events.k8s.io
    - backups.velero.io
    - restores.velero.io
    - resticrepositories.velero.io
    - csinodes.storage.k8s.io
    - volumeattachments.storage.k8s.io
    - backuprepositories.velero.io
