apiVersion: v1
kind: ServiceAccount
metadata:
  name: petclinic-app
  namespace: petclinic-demo
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: petclinic-app-role
  namespace: petclinic-demo
rules:
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: petclinic-app-rolebinding
  namespace: petclinic-demo
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: petclinic-app-role
subjects:
- kind: ServiceAccount
  name: petclinic-app
  namespace: petclinic-demo
